# Generated by Django 4.1 on 2022-10-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_date']},
        ),
    ]
