# Generated by Django 4.1 on 2023-02-08 21:14

import api.models.hero_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_herolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.hero_model.upload_to),
        ),
        migrations.AlterField(
            model_name='hero',
            name='move1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes_prim', to='api.move'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='move2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes_second', to='api.move'),
        ),
    ]
